# Tools for Collaborating {#GitHub}

## Overview & Learning Objectives
This chapter covers tools that will help you collaborate effectively with others on software and data analysis projects. 
This includes 
[Colaboratory](https://colab.research.google.com/), an online Jupyter notebook server;
[Git](https://git-scm.com/), a *version control* tool for maintaining, keeping track of, merging, and switching between different versions of code; and
[GitHub](https://github.com), a hosting service for Git repositories that helps you keep track of bugs, communicate with collaborators, share your project,
and keep it safely backed up in the cloud. By the end of this chapter, you'll be able to:

- [TODO] colab
- create a git code repository on GitHub
- download the repository to your own computer
- make changes to your code and upload them to GitHub
- download changes made by others from GitHub
- revert to an older version of your code

Here is a list of videos you might want to watch to familiarize yourself further with these tools, as well as a cheatsheet of Git and terminal commands.

## Why do we need special tools for this?
When you're working on your own

when you're working with others

What we want from a collaborative tool

## Working Online with Colab

what is colab

### Creating a notebook 

### Sharing a notebook

### Reverting a notebook 

### Best Practices


## Bigger Projects: Version Control with Git and GitHub

can you imagine realtime editing with your whole company? how distracting

What is git and github, difference

### Creating a Repository

### Downloading to Your Computer

### Best Practices

no big files
check what others have done before you work
issues



## Additional Resources

- bitbucket
- gitlab
- video links
- more advanced git tutorials
- git is distribution; no one master repository
- continual integration

branching, diffs, merging

## Videos to learn about version control with GitHub and Git

### Creating a GitHub repository
<iframe width="840" height="473" src="https://www.youtube.com/embed/HWR4IFV3n9s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Exploring a GitHub repository
<iframe width="840" height="473" src="https://www.youtube.com/embed/R8OAwrcMlRw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Directly editing files on GitHub
<iframe width="840" height="473" src="https://www.youtube.com/embed/uE2DxUfZjtE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Logging changes and pushing them to GitHub
<iframe width="840" height="473" src="https://www.youtube.com/embed/SIe-BBcfHcU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## Git command cheatsheet

Because we are writing code on a server, we need to use Git in the terminal to get files from GitHub, and to send back changes to the files that we make on the server. Below is a cheat sheet of the commands you will need and what they are for:

### Getting a repository from GitHub onto the server for the first time
*This is done only once for a repository when you want to copy it to a new computer.*
```
git clone https://github.com/USERNAME/GITHUB_REPOSITORY_NAME.git
```

### Logging changes
After editing and saving your files (e.g., a Jupyter notebook):
```
git add FILENAME
git commit -m "some message about the changes you made"
```

### Sending your changes back to GitHub
After logging your changes (as shown above):
```
git push
```

### Getting changes
To get the changes your collaborator just sent to GitHub onto your server:
```
git pull
```

## Terminal cheatsheet

We need to run the above Git commands from inside the repository/folder that we cloned from GitHub. To navigate there in the terminal, you will need to use the following commands:

### See where you are:
```
pwd
```

### See what is inside the directory where you are:
```
ls
```

### Move to a different directory
```
cd DIRECTORY_PATH
```

